### ISSUE TITLE
Event Reminder settings changes are difficult to test

### ISSUE THREAD

**Issue by sttelv** [Tharylia/Blish-HUD-Modules#112]
**Please name the module you want to request a feature for**
Event Table

**Is your feature request related to a problem? Please describe.**
a. It's very difficult to fine tune the settings for reminders (position, size, opacity).
b. It's also difficult to remember/make a note of what a good/optimal value for most settings would be, as we just get sliders, and no numerical values. The only values that are immediately obvious are 0 and 100%

**Describe the solution you'd like**
a. Either show a temporary reminder window for 1-2 seconds while modifying any of the settings or while the slider is "held down" (as a sort of preview) or add a checkbox to toggle a permanent test reminder on/off. It would also be nice if Reminder Left/Right Click Action can be tested on either the proposed permanent test reminder or the current temporary ones.
b. Add a text entry box immediately to the left of the sliders. There's enough space there, and it allows users to better understand what 25, 50, 75% opacity look like, or what size 5/10/20 look like, rather than guesstimating where abouts the slider is.

**Describe alternatives you've considered**
a. Better yet, allow us to temporarily sticky all test reminders (ignoring Reminder Duration, or setting it to 3600 seconds), so we can also see how it interacts with other UI elements - I want to place them above the chat, expanding upwards, but don't have the exact position and size of the squad/party windows, and testing how many reminders it takes to overlap with other UI elements would be difficult. Change opacity/height/width, test reminder x5 or x6, modify them, test x5 or x6 again.

That way I could say, spawn 7 test reminders (if I know I generally care about reminders for 7 events), join a full party/squad, and then change size x/y or location x/y and see it update dynamically, allowing me to see which height works best so there's no overlap between UI elements

**Additional context**
None

**Comment by Tharylia** [comment]
Showing values for sliders is definitely a point I understand and is on my list. I waited for core to implement this but I guess it's time to do it myself. 

The other stuff about permanent reminders that change based on the settings is kinda difficult to implement at this point. I will see how I can get that into the current implementation.

**Comment by sttelv** [comment]
I have no idea what the limitations you're working with are, but maybe spawning and destroying the test windows repeatedly while you're actively changing the setting would work? I don't know what kind of performance impact that could have, though. 

A "permanent" (toggleable) window would then technically behave exactly like the event table window, which does update in real-time if you change its x/y coordinates or style options. Maybe two buttons - "add persistent test window" (which can be clicked multiple times to stack multiple ones) and a "delete all persistent test windows" button?

**Comment by Tharylia** [comment]
Recreating the window every time something changes would be bad I think.
That would mean update for every pixel moved which could be thousands per second.

They are different from event areas as they need to stack on top of each other for example. That's the reason you can only specify a starting point currently and everything else is relativ to the one shown prior.

But I got to experiment a bit and see how things work out.

**Comment by sttelv** [comment]
I look forward to seeing what you come up with! And if someone wants to spam move the slider between 0 and 100 and see their FPS tank to single digits, I say let them.

**Comment by Tharylia** [comment]
This is implemented in the newest version

**Comment by sttelv** [comment]
Perfect! Thank you
