### ISSUE TITLE
Manage Events/Reminders - show category for enabled events/reminders

### ISSUE THREAD

**Issue by sttelv** [Tharylia/Blish-HUD-Modules#113]
**Please name the module you want to request a feature for**
Event Table

**Is your feature request related to a problem? Please describe.**
It's difficult to tell at a glance which events or reminders are enabled. Less so for events, but finding the category they're in, especially since the category order looks pretty arbitrary, is difficult.

**Describe the solution you'd like**
Provide a separate category under All Events/All Reminders called Enabled Events or Currently Enabled or Currently Active or whatever you like.

**Describe alternatives you've considered**
List all the enabled events/reminders first in the list, followed by the list as it is currently displayed 

**Additional context**
Adding sorting options for the categories, maybe except All Events/Day-Night cycle/Server Reset would be nice. Alphabetical/by release time would be good. It also feels like an arbitrary decision to have the newest metas be at the bottom (DE, Skywatch, Amnytas, Convergences), but have Invading Awakened be visible on the first page.

And tiny, tiny nitpick, but Manage Reminders belongs at the top of the window imo, same as Manage Events, not at the bottom.

**Comment by Tharylia** [comment]
There is an option to sort the manage events categories under general settings. The categories are sorted after release date by default (for the most part).

**Comment by Tharylia** [comment]
The "Manage Events" view has now a new menu item called "Enabled Events"
840d937fe078d2b7ea36d27aed335c60704d75ba

**Comment by Tharylia** [comment]
The buttons for the reminder settings have been moved to the top
532c8774f518d11efe0abf7cfc27bb0499f534dd

**Comment by Tharylia** [comment]
This is now live with version 3.8.0
