### ISSUE TITLE
Manage Events scroll bar overlaps with module info

### ISSUE THREAD

**Issue by sttelv** [Tharylia/Blish-HUD-Modules#117]
**Describe the bug**
In the All Events/Enabled Events (with enough enabled events) views, the scroll bar overlaps the individual event frames and partially overlaps the checkboxes

**To Reproduce**
Reminders > Manage Reminders > All Events
Also reproducible for Event Areas > Manage Events

**Expected behavior**
Scroll bar is to the right of the module display area

**Screenshots**
![image](https://github.com/Tharylia/Blish-HUD-Modules/assets/37104483/c3ae3251-90f0-4644-894a-254912a88e47)

**Error Submission Module**
Y

**Additional context**

**Comment by Tharylia** [comment]
Seems like my fix for the width was not enough. I will take a look later.

**Comment by Tharylia** [comment]
The fix will be available in the next version. I can name any ETA as I need to fix some other bugs first.
