### ISSUE TITLE
Icons for SOTO metas

### ISSUE THREAD

**Issue by klearscreen** [Tharylia/Blish-HUD-Modules#119]
**Please name the module you want to request a feature for**
Event Table

**Is your feature request related to a problem? Please describe.**
No, it's just the codes for the SOTO icons.

**Describe the solution you'd like**
I'd like the event icons for the SOTO maps to follow the same pattern from the other events: [3124846.png](https://wiki.guildwars2.com/wiki/File:Skywatch_Archipelago.png) for Skywatch Archipelago and [3124847.png](https://wiki.guildwars2.com/wiki/File:Amnytas.png) for Amnytas.

**Describe alternatives you've considered**
I made my own events with the icons.

**Comment by Tharylia** [comment]
Sure! I will change that later

**Comment by Tharylia** [comment]
Fixed! Should be live in about 20 mins
