### ISSUE TITLE
Custom events won't copy their waypoint

### ISSUE THREAD

**Issue by klearscreen** [Tharylia/Blish-HUD-Modules#127]
**Describe the bug**
Custom events won't copy their waypoint when clicked

**To Reproduce**
1. Create a custom event
2. Wait for it to update in your client
3. Left click on it within the game

**Expected behavior**
I expect a pop-up saying that the waypoint has been copied, and the clipboard to have the custom waypoint from the event.

**Error Submission Module**
Yes, I am using the `Error Submission Module`.

**Additional context**
Waypoints are correctly copied from the default events.

**Comment by Tharylia** [comment]
Oh I think that's an regression introduction from changes in #115
I will see to get that fixes in the backend

**Comment by Tharylia** [comment]
I rolled out a hotfix in the backend. In my tests it does not happen anymore. Please test that on your and tell me if that is also fixed.

**Comment by klearscreen** [comment]
It's fixed!
