### ISSUE TITLE
[BUG/FEATURE] Event Table ....

### ISSUE THREAD

**Issue by cranos5000** [Tharylia/Blish-HUD-Modules#131]
**Message**:
backend unavaliable: SAYS IT CANT CONNECT THEREFOR IT CANT SHOW THE EVENTS"(

**Discord**: cranos5000

**This Issue was created automatically by the module Event Table**

**Comment by Tharylia** [comment]
It seems to be caused by dns problems at the moment. Hopefully it's gone by tomorrow.
