### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by Idaya1** [Tharylia/Blish-HUD-Modules#132]
**Describe the bug**
site is down error 404

**Comment by Tharylia** [comment]
What site do you mean?

**Comment by Idaya1** [comment]
Your live map from guildwars 2

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tharylia** [comment]
Sorry I forgot to migrate that domain.

Nonetheless there are currently some general dns problems with my services. I hope its gone by tomorrow.

**Comment by Tharylia** [comment]
Sorry I forgot to migrate that domain.

Nonetheless there are currently some general dns problems with my services. I hope its gone by tomorrow.

**Comment by Idaya1** [comment]
I know that sort of Problems 😅

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
