### ISSUE TITLE
Navigate to Waypoint bug

### ISSUE THREAD

**Issue by Zathalyn** [Tharylia/Blish-HUD-Modules#140]
**Describe the bug**
Navigate to Waypoint doesn't work unless it is on primary monitor

**To Reproduce**
1. open the game on your primary monitor
2. Move game window to another monitor
3. Make module is set to "navigate to waypoint"
4. try teleporting by clicking on something in the event table
5. map will open but won't move at all and display the error "failed to navigate to waypoint"

**Expected behavior**
should move around the map and navigate to waypoint

**Screenshots**

**Error Submission Module**
Are you using the `Error Submission Module`? Yes/No
Yes

**Additional context**
Add any other context about the problem here. For example your Log

**Comment by Tharylia** [comment]
The map navigation has some flaws. I will try investigating this.

**Comment by Tharylia** [comment]
Closing in favor of #66
