### ISSUE TITLE
[WINE] Event Table Crashes Blish HUD Shortly After Starting

### ISSUE THREAD

**Issue by FuzzyWuggzy** [Tharylia/Blish-HUD-Modules#152]
**Describe the bug**
I've been using Blish HUD with a few modules for months now with no issues (the one's I use are listed in the log), then today I install the Event Table module and after enabling it Blish HUD runs normally for a few seconds (even the event table updates) then crashes. Restarting Blish HUD repeats the cycle. I'm running GW2 (and Blish HUD) under WINE-GE 8.26 in it's own dedicated prefix, host OS is Fedora 40. Thank you for taking the time to look at my issue.

**To Reproduce**
1. Start GW2 and Blish HUD 1.2.0
2. With the Event Table module enabled wait a few seconds
3. Blish HUD crash

**Expected behavior**
Not crash.

**Screenshots**
![Screenshot_20241028_171603](https://github.com/user-attachments/assets/a9145442-d678-42e0-8a44-afa5e8f799ab)

**Error Submission Module**
Are you using the `Error Submission Module`? No

**Additional context**
Here's the Blish HUD log: [blishhud.20241028-170226.log](https://github.com/user-attachments/files/17546427/blishhud.20241028-170226.log)

**Comment by Tharylia** [comment]
This behavior is known. It's caused by some missing implementations in WINE for OS notifications.
I'm linking specific wine builds for every release as the one in the normal blish repo does not work.

Have a look here: https://pkgs.blishhud.com/estreya.bh.eventTable.html#v3.15.0

Just drop the downloaded .bhm file into your modules folder and delete the other event table file downloaded by the repo.

**Comment by FuzzyWuggzy** [comment]
Thank you for responding and providing a link, I'm also sorry that I didn't find it myself, I should've looked around more.

Unfortunately the module still crashes Blish HUD, now without any errors in the log. I renamed the settings.json so that it would generate a new one and only enabled this module,  but that didn't help either.

Here's the new log: [blishhud.20241028-184058.log](https://github.com/user-attachments/files/17547464/blishhud.20241028-184058.log)

**Comment by Tharylia** [comment]
Sorry for the late reply!

I would need some form of error message I'm afraid :/

**Comment by FuzzyWuggzy** [comment]
That's okay, thank you for getting back to me.

I understand, I mean it would be unreasonable to expect you to debug without a proper error log. Maybe it's a regression in Wine that'll hopefully get fixed.

Take care.
