### ISSUE TITLE
Event Table: Suggestion/Wish: Only show current zone.

### ISSUE THREAD

**Issue by Naladdar** [Tharylia/Blish-HUD-Modules#24]
**Please name the module you want to request a feature for**
Event Table

**Is your feature request related to a problem? Please describe.**
NO!

**Describe the solution you'd like**
What i really would like, would be an option to only show events in the current zone. I like to have an bar at top of my screen showing whats going on in the current zone, when will be the meta and so on. Currently that's not possible (Or i am just to darn blind!)

**Comment by Tharylia** [comment]
That should be possible. I have added that to my list.

**Comment by Naladdar** [comment]
Danke, danke, danke!

Like every update i checked for the changes, hoping that gets included. Today was the day!

Thanks alot, you are my champ for today and made my evening better! ;-)

Thats such a incredible good and usefull mod.
