### ISSUE TITLE
Event Table: Cross & Change Opacity completion action breaks marking event completed

### ISSUE THREAD

**Issue by MHannila** [Tharylia/Blish-HUD-Modules#57]
**Describe the bug**
Module: Event Table
Version: v3.3.0
Marking events as done does not work when "Cross & Change Opacity" is the selected completion action.

**To Reproduce**
1. Go to "Settings" -> "Event Areas"
2. Set "Completion Action" to "Cross & Change Opacity"
3. Right click any event and select "Finish"
4. Nothing happens

**Expected behavior**
Expected behavior would be for the event to get marked as completed. It works for "Crossout", "Hide", and "Change Opacity" options and the events are correctly crossed out and opacity changed if they are marked finished with any of the working options active and _then_ changing to the "Cross & Change Opacity".

**Screenshots**
I don't feel these will help, but I can provide them later if needed.

**Error Submission Module**
Are you using the `Error Submission Module`? No

**Additional context**
None

**Comment by Tharylia** [comment]
Alright, I could identify this problem. 
I have forgotten to add the option "Crossout & Change Opacity" to the function "FinishEvent".

Thanks for the report!
