### ISSUE TITLE
Event Table - Leyline Anomaly Event completion

### ISSUE THREAD

**Issue by Dreamthrum** [Tharylia/Blish-HUD-Modules#69]
**Please name the module you want to request a feature for**
Event Table

**Is your feature request related to a problem? Please describe.**
No

Hey, would be nice to have the all 3 LLA events removed automatically once you completed one of them, there's no use on doing more, you only get the rewards daily.

**Comment by Dreamthrum** [comment]
By "removed" I meant hidden until the next reset

**Comment by Tharylia** [comment]
Will be available with version 3.10.0
