### ISSUE TITLE
Event Table fatal error

### ISSUE THREAD

**Issue by svefn** [Tharylia/Blish-HUD-Modules#72]
I have the latest Blish HUD v1.1.1, reinstalled Event Table v3.4.2 a few times but it still gives fatal error, is it a problem on my end or not?

**Comment by Tharylia** [comment]
When did this start happening for you?
I started some backend maintenance about 30 mins ago and finished 5 mins ago.
That would have caused a fatal error in the current version of event table.

Can you verify if the problem still exists?

**Comment by svefn** [comment]
Around the time I posted. It is working now though, maybe your maintenance fixed it :)

**Comment by Tharylia** [comment]
No, the maintenance was the cause of your issue then.
The module is expected to get a fatal error as it's useless without my backend anyway.
Sadly there is no custom message modules can display there.
