### ISSUE TITLE
Event Table - Reminder: Add config option for click on event popup

### ISSUE THREAD

**Issue by DamDam0887** [Tharylia/Blish-HUD-Modules#74]
**Please name the module you want to request a feature for**
Event Table - Reminder

**Is your feature request related to a problem? Please describe.**
Not being able to easily go to the reminded event.

**Describe the solution you'd like**
Add and config option to set an on-click behaviour for the reminder popups (same as for the event areas part : "Copy waypoint" and "Navigate to waypoint")

**Comment by Tharylia** [comment]
Good idea 👍
