### ISSUE TITLE
Event Table - Reminders: Configure default reminder times

### ISSUE THREAD

**Issue by DamDam0887** [Tharylia/Blish-HUD-Modules#75]
**Please name the module you want to request a feature for**
Event Table - Reminders

**Is your feature request related to a problem? Please describe.**
Unable to configure the default times for the reminder

**Describe the solution you'd like**
Add a section which would contain all the default reminder times (I think there are 2 or 3 by default) with the possibility to add or remove, and which would apply to all events unless munually overwritten by specific setups on specific events.

I'd see something like this (which would folow the already present UI) :

[ Change default reminder times ]
0 10 0 Remove
0 7 30 Remove
Add

---
These would be totally overridden for events for which the user has configured specific times (with the already existing feature).

**Additional note on a related matter**

It would also be nice to have a warning in the "Change all Reminder Times" window, to tell us how the feature overwrites all specific reminder times currently set up by the user, which may mean potential loss of "data".

**Comment by Tharylia** [comment]
That feature is already a thing. Have a look at the reminders tab and the button called "Change all reminders times".

**Comment by DamDam0887** [comment]
It is not at all what I suggested. I'd actually want the inverse of the current feature.

The current feature seems to overwrite all custom event times. I'd like to have to oposite : to be able to change only the default times and keep the customized ones.

Am I actually missing something in how it works ?

**Comment by Tharylia** [comment]
Ohh I gotcha. Sorry I read that wrong at 2am 😄
I will try and see what I can do about that.

**Comment by Tharylia** [comment]
Released with v3.5.0-beta.1
