### ISSUE TITLE
Event Table: Font or Kerning tweaks

### ISSUE THREAD

**Issue by DragonRulerX** [Tharylia/Blish-HUD-Modules#76]
**Please name the module you want to request a feature for**
Event Table

**Is your feature request related to a problem? Please describe.**
Just noticing on some of my displays that this font is a bit hard to read. 

He's an example of where I think it could help - the 2:01:2 in this image is not very clear to me.
![image](https://github.com/Tharylia/Blish-HUD-Modules/assets/22264652/92a8f5ff-01e4-442b-adbc-60a938446e3c)

**Describe the solution you'd like**
For stuff like this I'd probably prefer a monospaced font or a way to adjust the kerning (space between characters) to give a little better distinction between letters - particularly around the colons. I noticed you had the option to adjust the font size already, but I think giving the option to change the font family would be helpful too for those seeking a monospaced format.

**Describe alternatives you've considered**
No real alternatives beyond getting a different monitor and even that may or may not fix it.

**Additional context**
See above screenshot

**Comment by Tharylia** [comment]
I get this request a lot. Unfortunately blish does not support other fonts at the moment.
I think you could compile a ttf file to monogamy and replace to memonia font files to trick blish into changing it.
But I have no idea how to do that.

Freesnöw l, the developer of blish core, said he wanted to introduce font changing. But this requires a lot of work and breaking changes for modules.
I will give him a poke and ask for the status.

**Comment by Tharylia** [comment]
Released with v3.5.0-beta.1
