### ISSUE TITLE
Event Table: Copy and Rename Features

### ISSUE THREAD

**Issue by DragonRulerX** [Tharylia/Blish-HUD-Modules#77]
**Please name the module you want to request a feature for**
Event Table

**Is your feature request related to a problem? Please describe.**
Just got done designing the original "Main" layout and found out I could add more layouts which is neat. Realized there was no way to copy my previous layout or rename a layout once it is made which is not so neat.

**Describe the solution you'd like**
I'd like a way to copy a previous layout and a way to rename a layout (perhaps even a reorder feature? - I haven't checked if this is a thing yet or not tbf)

**Describe alternatives you've considered**
The only alternative I can think of is finding the saved configuration file locally and copying w/e content is necessary with the appropriate tweaks, but that seems excessive and unrealistic for normal users.

**Additional context**
I'm pretty new to Blish so I'm just learning everything and could be blind to an obvious existing option.

**Comment by Tharylia** [comment]
That sounds like a good addition.
I will try and implement that.

**Comment by Tharylia** [comment]
I won't implement a rename function as all associated settings are saved with the name included. I think with the new copy function you can have your rename fairly easily now 😄

**Comment by Tharylia** [comment]
Released with v3.5.0-beta.1
