### ISSUE TITLE
Event Table: Displays Settings screen without prompt

### ISSUE THREAD

**Issue by DragonRulerX** [Tharylia/Blish-HUD-Modules#78]
**Describe the bug**
[Copying original messages from Discord for context]

[1:24 AM]
Not sure what is up with this, but when I enter or leave combat the settings configuration screen is constantly popping up.

[1:38 AM]
Actually, I began to realize there was a "submit bug" option back on the module home screen (not in the settings screen - probably should be in there tbh too) and then using that option sent me to github, but then crashed blish after authorizing but failing to create the bug ticket. This crash caused me to restart blish and now stuff is magically working 🤔 . Seems like something that should be either indicated as a necessary step or something that needs to be addressed.

**To Reproduce**
Steps to reproduce the behavior (guess):
1. Install the module for the first time (not sure if anything gets cached if it's an uninstall->reinstall situation)
2. Toggle a ton of random settings (no clue which ones did it - if any)
3. Attempt to kill things in game -> settings screen just pops up
4. From the Event Table module screen attempt to create a bug (ensure GitHub doesn't have permissions yet)
5. At this point I got an error and attempted to close and re-open screens to get the bug to submit until Blish just crashed.
6. Restart Blish and things work

**Expected behavior**
Steps 1 and 2 should work out of the box. Step 3 should not happen (ensured keybinds weren't related). Steps 4 and 5 should not yield a crash necessitating Step 6.

**Screenshots**
Now that it's not broken I have no ability to reproduce this - sorry :(

**Error Submission Module**
Given I don't know what this is - no?

**Additional context**
Redacted Log: [blishhud.20230901-231632.log](https://github.com/Tharylia/Blish-HUD-Modules/files/12503395/blishhud.20230901-231632.log)

**Comment by Tharylia** [comment]
The settings screen should not display by itself. The only time it will do so is the following:

- window is open
- dynamic hud option in blish is set to hide on combat
- you go into combat

Have a look at your dynamic hud settings for blish (not the game!)

As for creating github issues:
Its a fairly fragile process. I will look into that a bit.

**Comment by DragonRulerX** [comment]
These are my current dynamic hud configurations - I think?
![image](https://github.com/Tharylia/Blish-HUD-Modules/assets/22264652/f324567c-fe07-4114-b914-4f5549417354)
I'm pretty new to Blish so please tell me if I ever give you the wrong details.

I do notice there is a "Show Only Out of Combat" option, but that feels like that shouldn't be relevant to spawning the window on engagement with a foe? Again, sadly the restart of Blish somehow fixed this so I can't check to see if your suggested configuration would have resolved the issue. Also, I want to say even a foe attacking me while idle (so no key press) was spawning the window - if that helps in any way?

**Comment by Tharylia** [comment]
The settings seem fine. I'm not to sure either why that would have happened 😕

**Comment by Tharylia** [comment]
The problem with the windows popping up seems to be a broken core implementation: https://discord.com/channels/531175899588984842/534492012263636992/1148305158468534422

Nothing I can do until a fix is found.
