### ISSUE TITLE
Cannot edit a category

### ISSUE THREAD

**Issue by klearscreen** [Tharylia/Blish-HUD-Modules#82]
**Describe the bug**
I cannot add events to a category or delete it. Trying to add an event gives an error and trying to delete the category doesn't give any feedback.

**To Reproduce**
1. Go to 'Event Table'
2. Click on 'Manage Custom Events'
3. Select the appropriate category
4. Click on 'Add Event'
5. Add appropriate Key and Name
6. Click on 'Save'
7. See error
8. Click on 'Delete' to delete the category
9. No feedback

**Expected behavior**
I expect to be able to add events or delete a category.

**Screenshots**
https://snipboard.io/xUKd6f.jpg

**Error Submission Module**
I am using 'Error Submission Module'.

**Additional context**
I created dummy category and event before creating this erratic category, both had names and keys as 'xxxxxxxxxxxxxxxxxx'.

**Comment by Tharylia** [comment]
Thats strange..
It works perfect on my end. Can you try and see if the error still exists?

**Comment by klearscreen** [comment]
Yup, it still persists.

**Comment by Tharylia** [comment]
Can you open the dev tools of your browser, select the network tab, try the action again and make a screenshot of the network tab? 

If you need more detailed instructions how to do that let me know.

**Comment by klearscreen** [comment]
Here you go:
https://snipboard.io/rqG7Hs.jpg

**Comment by Tharylia** [comment]
That interesting.. 
Can you verify for me that the "transferred" field of the first red line says something like "CORS Missing Allow Origin"?
If yes, please click it and make a screenshot of the headers page.

Additionally please tell me what the "transferred" field of the second line says.
Please make a screenshot of the header page as well.

Are you using some kind of VPN?

**Comment by klearscreen** [comment]
The headers page of the first red line shows this:
https://snipboard.io/69YiO0.jpg

Its text is as follows:
scheme
	https
host
	api.estreya.de
filename
	/blish-hud/v1/event-table/custom/categories/f&297%2vMXfBg2MXF*/events
Address
	89.58.53.212:443
Status
404
Not Found
VersionHTTP/1.1
Transferred159 B (0 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem

	
Connection
	close
Content-Length
	162
Content-Type
	text/html
Date
	Sat, 09 Sep 2023 18:36:06 GMT
Server
	nginx/1.18.0 (Ubuntu)
	
Accept
	*/*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	en-US,en;q=0.5
Access-Control-Request-Headers
	authorization,content-type
Access-Control-Request-Method
	POST
Connection
	keep-alive
DNT
	1
Host
	api.estreya.de
Origin
	https://blish-hud.estreya.de
Referer
	https://blish-hud.estreya.de/
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-site
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0

The second red line has "NS_ERROR_DOM_BAD_URI" for its transferred field:
https://snipboard.io/h2DEFp.jpg

Its text is as follows:
<html><body>
<div class="headers-overview"><div class="url-preview"><div class="properties-view"><div class="tree-container">

scheme | https
-- | --
host | api.estreya.de
filename | /blish-hud/v1/event-table/custom/categories/f&297%2vMXfBg2MXF*/events


</body>
</html>scheme
	https
host
	api.estreya.de
filename
	/blish-hud/v1/event-table/custom/categories/f&297%2vMXfBg2MXF*/events
Transferred0 GB (0 GB size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest
DNS ResolutionSystem

	
Accept
	application/json, text/plain, */*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	en-US,en;q=0.5
Authorization
	Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzMWZmODY2LWU3YmEtNGE1NS1iZDE4LTNmODlmYzJjMTlmNCIsInVzZXJuYW1lIjoiRnJlbnp5NzA0NiIsImVtYWlsIjoidGVsZXZpc2VkX2thdHptYWllckBzaW1wbGVsb2dpbi5jb20iLCJyaWdodHMiOnsibmF2aWdhdGlvbi5ldmVudFRhYmxlIjp0cnVlLCJuYXZpZ2F0aW9uLmV2ZW50VGFibGUubWFuYWdlQ3VzdG9tRXZlbnRzIjp0cnVlLCJwYWdlLmV2ZW50VGFibGUubWFuYWdlQ3VzdG9tRXZlbnRzIjp0cnVlfSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY5NDI4MTE1OCwiZXhwIjoxNjk0Mjg0NzU4LCJpc3MiOiJFc3RyZXlhIEJsaXNoIEhVRCBBUEkifQ.EooRsUy0aTdQWBHmxltB_zEKbR2rVoFMnIts6A025JY
Connection
	keep-alive
Content-Length
	34
Content-Type
	application/json
DNT
	1
Host
	api.estreya.de
Origin
	https://blish-hud.estreya.de/
Referer
	https://blish-hud.estreya.de/
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-site
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0

I currently am using a VPN but the error shows on different computers with different browsers and settings, including my cellphone and computers without a VPN.

**Comment by Tharylia** [comment]
Ohh okay I think I see the error.
You gave the category a key with % in it.
I'm currently not encoding that. Can you try deleting the entire category and give it a simple key and try again?

**Comment by klearscreen** [comment]
Sadly I cannot, nothing happens when I try to delete the category not even an error message, but I get the following network errors:
https://snipboard.io/pOjlos.jpg

**Comment by Tharylia** [comment]
That makes sense. I didn't think of this.
I will fix this later when I get to my PC. Then you shouldn't have to delete anything.

**Comment by Tharylia** [comment]
Okay I have deployed a potential fix for this. Please try again.
