### ISSUE TITLE
Event Table (Event Areas - Reminders Integration)

### ISSUE THREAD

**Issue by Dolvic** [Tharylia/Blish-HUD-Modules#84]
**Please name the module you want to request a feature for**
Event Table

**Is your feature request related to a problem? Please describe.**
I frequently change my configured reminders based on what I'm doing that game session. Since the Event Table gives an easy way to see all the various events across the game, I like using it to plan out the session.

**Describe the solution you'd like**
A right click option for an event in the event table that allows me to toggle the reminder state for that event. E.g. if Shatterer is up in 30 minutes and I feel like doing it that day, I'd right click on it and turn on its reminder while I do other stuff in the meantime.

**Describe alternatives you've considered**
Right now I manually note the event name and then look it up in the reminders config window.

**Additional context**
![image](https://github.com/Tharylia/Blish-HUD-Modules/assets/3219755/f2198716-eeb6-4cb8-9888-fbeab66fd9b2)
An additional option here to toggle the reminder.

**Comment by Tharylia** [comment]
This is available since version 3.9.0
