### ISSUE TITLE
Event-Table Ley-line Anomaly Tooltip big/issue

### ISSUE THREAD

**Issue by Udderdog** [Tharylia/Blish-HUD-Modules#93]
**Describe the bug**
Ley-line Anomaly has no tooltip (location, time) when moused over and wont let me copy waypoint. The rest of the events will.

**To Reproduce**
1. Add all three ley-line to events to table, and other events
2. Mouse over ley-line, mouse over any other event
3. See no tooltip vs tooltip.

**Expected behavior**
A tooltip with event name, location, time (finished, next start)

**Error Submission Module**
I tried to submit using blish hud but wouldn't work.

**Comment by Udderdog** [comment]
Also, can't right click Ley-Line  for drop down menu.

**Comment by Tharylia** [comment]
I are probably running into a known bug with filler events. can you teat if the problem persists when you disable filler events?

Either way, it should fix itself after a bit when fillers a reloaded

**Comment by Udderdog** [comment]
i took a break and it works, with fillers on.  /shrug.

Thank you and good luck.
