### ISSUE TITLE
Event Title

### ISSUE THREAD

**Issue by freelance747** [Tharylia/Blish-HUD-Modules#94]
**Message**:
When I click on te name/event, it says Not Found

**Discord**: 

**This Issue was created automatically by the module Event Table**

**Comment by Tharylia** [comment]
Please check if the module has loaded completely. If it is the case please remove this folder and restart blish and wait for the module to load completely (see loading spinner under icon at top left):

`%USERPROFILE%\Documents\Guild Wars 2\addons\blishhud\events\pois`

**Comment by freelance747** [comment]
Thank you for the response. It still is the same. I added a screenshot.Hope this helps. Sent from Mail for Windows From: EstreyaSent: Friday, 27 October 2023 5:40 PMTo: Tharylia/Blish-HUD-ModulesCc: freelance747; AuthorSubject: Re: [Tharylia/Blish-HUD-Modules] Event Title (Issue #94) Please check if the module has loaded completely. If it is the case please remove this folder and restart blish and wait for the module to load completely (see loading spinner under icon at top left):%USERPROFILE%\Documents\Guild Wars 2\addons\blishhud\events\pois—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Tharylia** [comment]
I think you need to paste the screenshot directly on github
 Something broke here with the email reply

**Comment by freelance747** [comment]
ok will do. adding 2 screenshots.

![gw010](https://github.com/Tharylia/Blish-HUD-Modules/assets/85811138/1b0733d6-ea2a-4418-8623-22e153ff97a8)
![gw011](https://github.com/Tharylia/Blish-HUD-Modules/assets/85811138/8bbb6a61-eef1-4759-9a95-35da67f2a543)

**Comment by Tharylia** [comment]
You have to take a screenshot of your whole screen and not just gw2. Blish is not part of the game just an overlay

**Comment by Tharylia** [comment]
Do you still have this issue?
