### ISSUE TITLE
[BUG/FEATURE] Event Table ....

### ISSUE THREAD

**Issue by ArtistOrion** [Tharylia/Blish-HUD-Modules#95]
**Message**:
Event table is freezing/crashing my BlishHUB very frequently with the same error.  Here is the copy and pasted error log segment.

21:48:38.6725 | INFO  | Blish_HUD.ModuleService | Unloading module "Event Table (estreya.bh.eventTable) v3.6.0".
21:48:38.6725 | DEBUG | Blish_HUD.Modules.Module | Module "Event Table (estreya.bh.eventTable) v3.6.0" run state changed to Unloading
21:48:38.6725 | ERROR | Blish_HUD.Modules.ModuleManager | Module '"Event Table (estreya.bh.eventTable) v3.6.0" threw an exception while unloading.
SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.PlatformInitialize()
   at Microsoft.Xna.Framework.Graphics.Effect.Clone(Effect cloneSource)
   at Microsoft.Xna.Framework.Graphics.Effect.Clone()
   at Blish_HUD.Controls.Effects.ScrollingHighlightEffect..ctor(Control assignedControl) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Effects\ScrollingHighlightEffect.cs:line 72
   at Blish_HUD.Controls.ContextMenuStripItem..ctor() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\ContextMenuStripItem.cs:line 59
   at Blish_HUD.Modules.UI.Presenters.ManageModulePresenter.BuildClearSettingsMenuItem() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\UI\Presenters\ManageModulePresenter.cs:line 107
   at Blish_HUD.Modules.UI.Presenters.ManageModulePresenter.DisplaySettingMenu() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\UI\Presenters\ManageModulePresenter.cs:line 87
   at Blish_HUD.Modules.UI.Presenters.ManageModulePresenter.InvalidateViewState(Boolean staticDetails, Boolean stateDetails, Boolean stateOptions) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\UI\Presenters\ManageModulePresenter.cs:line 71
   at Blish_HUD.Modules.Module.OnModuleRunStateChanged(ModuleRunStateChangedEventArgs e) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\Module.cs:line 25
   at Blish_HUD.Modules.Module.DoUnload() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\Module.cs:line 153
   at Blish_HUD.Modules.Module.Dispose(Boolean disposing) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\Module.cs:line 214
   at Blish_HUD.ModuleService.Unload() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\ModuleService.cs:line 394

21:48:38.6725 | FATAL | Blish_HUD.DebugService | Blish HUD encountered a fatal crash!
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Graphics.Effect.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.Game.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.Game.Dispose()
   at Blish_HUD.Program.Main(String[] args) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Program.cs:line 93

**Discord**: eldestorion

**This Issue was created automatically by the module Event Table**

**I edited this afterwards to put in the error log properly**

**Comment by ArtistOrion** [comment]
**---System Information---**

**Time**: 11/18/2023, 21:58:57
**MachineName**: BLACK-BOX
**MachineId**: {C157D8F5-7EEE-41E8-9AB8-F1BEE9C9451D}
**OperatingSystem**: Windows 10 Home 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
**Language**: English (Regional Setting: English)
**SystemManufacturer**: Micro-Star International Co., Ltd.
**SystemModel**: MS-7E12
**BIOS**: 1.33
**FirmwareType**: UEFI
**Processor**: AMD Ryzen 7 7800X3D 8-Core Processor            (16 CPUs), ~4.2GHz
**Memory**: 65536MB RAM
**AvaliableOSMem**: 64668MB RAM
**PageFile**: 68141MB used, 8845MB available
**WindowsDir**: C:\WINDOWS
**DirectXVersion**: DirectX 12
**DXSetupParameters**: Not found
**UserDPISettings**: 96 DPI (100 percent)
**SystemDPISettings**: 96 DPI (100 percent)
**DWMDPIScaling**: Disabled
**DxDiagVersion**: 10.00.19041.3570
**DxDiagUnicode**: 1
**DxDiag64Bit**: 1
**Miracast**: Available, with HDCP
**MSHybrid**: Not Supported
**DirectXDatabaseVersion**: 1.0.8

**---Display Devices---**

**CardName**: AMD Radeon RX 6700 XT
**Manufacturer**: Advanced Micro Devices, Inc.
**ChipType**: AMD Radeon Graphics Processor (0x73DF)
**DACType**: Internal DAC(400MHz)
**DeviceType**: Full Device (POST)
**DeviceKey**: Enum\PCI\VEN_1002&DEV_73DF&SUBSYS_232D1458&REV_C1
**DeviceStatus**: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
**DeviceProblemCode**: No Problem
**DriverProblemCode**: Unknown
**DisplayMemory**: 44575 MB
**DedicatedMemory**: 12242 MB
**SharedMemory**: 32333 MB
**CurrentMode**: 2560 x 1440 (32 bit) (144Hz)
**HDRSupport**: Not Supported
**Topology**: Extend
**ColorSpace**: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
**ColorPrimaries**: Red(0.667969,0.331055), Green(0.299805,0.625000), Blue(0.142578,0.051758), White Point(0.313477,0.329102)
**Luminance**: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
**MonitorName**: Generic PnP Monitor
**MonitorModel**: XF270HU
**MonitorId**: ACR0549
**NativeMode**: 2560 x 1440(p) (59.951Hz)
**OutputType**: Displayport External
**Eotf2084Supported**: 0
**BT2020YCC**: 0
**BT2020RGB**: 0
**AdvancedColorEnabled**: 0
**AdvancedColorSupported**: 0
**bCheckedMonitorCapabilities**: 1
**PixelFormat**: DISPLAYCONFIG_PIXELFORMAT_32BPP
**MonitorMaxRes**: Unknown
**DriverName**: C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\amdxc64.dll
**DriverFileVersion**: 31.00.22011.4008
**DriverVersion**: 31.0.22011.4008
**DriverLanguage**: English
**DDIVersion**: 12
**FeatureLevels**: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
**DriverModel**: WDDM 2.7
**DriverBeta**: 0
**DriverDebug**: 0
**DriverDate**: 9/20/2023 7:00:00 PM
**DriverSize**: 1857032
**DriverWHQLLogo**: Yes
**WHQLDateStamp**: Unknown
**VDD**: unknown
**MiniVDD**: unknown
**MiniVDDDate**: Unknown
**MiniVDDSize**: 0
**DeviceIdentifier**: {D7B71EE2-309F-11CF-4078-D6566EC2D235}
**VendorID**: 0x1002
**DeviceID**: 0x73DF
**SubSysID**: 0x232D1458
**RevisionID**: 0x00C1
**DriverNodeStrongName**: oem41.inf:cb0ae414fb83800b:ati2mtag_Navi22:31.0.22011.4008:PCI\VEN_1002&DEV_73DF&REV_C1
**RankOfInstalledDriver**: 00CF2000
**DXVAModes**: Unknown
**DXVA2Modes**: {C58B9A06-7E89-11E1-BB00-70B34824019B}  DXVA2_ModeMPEG2_VLD  {86695F12-340E-4F04-9FD3-9253DD327460}  DXVA2_ModeH264_VLD_NoFGT  {4245F676-2BBC-4166-A0BB-54E7B849C380}  {9901CCD3-CA12-4B7E-867A-E2223D9255C3}  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeVC1_VLD  {CA15D19A-2B48-43D6-979E-7A6E9C802FF8}  {D1C20509-AE7B-4E72-AE3B-49F88D58992F}  DXVA2_ModeHEVC_VLD_Main  {EA72396A-67EC-4781-BEDE-56F498F04EF2}  {C152CA8F-738C-461B-AD89-FC292CF8F162}  {514A356C-7027-4AFF-8A60-AFD2C1F672F1}  DXVA2_ModeHEVC_VLD_Main10  {65D1FA41-58AF-453A-9CAB-5D981156DA9F}  {2DB154B6-DBB2-4079-A3FF-60D7A898A6AB}  {C74A3FD0-D713-4581-A02E-8EDFB112ACE3}  DXVA2_ModeVP9_VLD_Profile0  DXVA2_ModeVP9_VLD_10bit_Profile2  {B8BE4CCB-CF53-46BA-8D59-D6B8A6DA5D2A}  {603A4756-A864-4F91-BB62-2C935B7A1391}  {84AD67F6-4C21-419A-9F0B-24F0578906C1}  
**GraphicsPreemption**: Primitive
**ComputePreemption**: DMA
**Miracast**: Not Supported by Graphics driver
**DetachableGPU**: No
**HybridGraphicsGPUType**: Not Supported
**PowerManagementPStates**: Not Supported
**VirtualGPUSupport**: Paravirtualization 
**BlockList**: DISABLE_HWSCH
**DriverCatalogAttributes**: Universal:False Declarative:True 
**MPOMaxPlanes**: 3
**MPOCaps**: ROTATION,VERTICAL_FLIP,HORIZONTAL_FLIP,BILINEAR,HIGH_FILTER,IMMEDIATE,HDR (MPO3)
**MPOStretch**: 1.000X - 1.000X
**MPOMediaHints**: rotation, resizing, colorspace Conversion 
**MPOFormats**: R16G16B16A16_FLOAT,R10G10B10A2_UNORM,R8G8B8A8_UNORM,B8G8R8A8_UNORM
**PanelFitterCaps**: STRETCH_RGB
**PanelFitterStretch**: 16.000X - 0.167X
**HardwareSchedulingAttributes**: Supported:False Enabled:False 
**DXVADeinterlaceCaps**: 
**D3D9Overlay**: Not Supported
**DXVAHD**: Not Supported
**DDrawStatus**: Enabled
**D3DStatus**: Enabled
**AGPStatus**: Enabled

**----------------**

**CardName**: AMD Radeon RX 6700 XT
**Manufacturer**: Advanced Micro Devices, Inc.
**ChipType**: AMD Radeon Graphics Processor (0x73DF)
**DACType**: Internal DAC(400MHz)
**DeviceType**: Full Device (POST)
**DeviceKey**: Enum\PCI\VEN_1002&DEV_73DF&SUBSYS_232D1458&REV_C1
**DeviceStatus**: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
**DeviceProblemCode**: No Problem
**DriverProblemCode**: Unknown
**DisplayMemory**: 44575 MB
**DedicatedMemory**: 12242 MB
**SharedMemory**: 32333 MB
**CurrentMode**: 1920 x 1080 (32 bit) (144Hz)
**HDRSupport**: Not Supported
**Topology**: Extend
**ColorSpace**: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
**ColorPrimaries**: Red(0.648438,0.332031), Green(0.326172,0.624023), Blue(0.157227,0.057617), White Point(0.313477,0.329102)
**Luminance**: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
**MonitorName**: Dell D2719HGF(HDMI)
**MonitorModel**: D2719HGF
**MonitorId**: DELA135
**NativeMode**: 1920 x 1080(p) (60.000Hz)
**OutputType**: HDMI
**Eotf2084Supported**: 0
**BT2020YCC**: 0
**BT2020RGB**: 0
**AdvancedColorEnabled**: 0
**AdvancedColorSupported**: 0
**bCheckedMonitorCapabilities**: 1
**PixelFormat**: DISPLAYCONFIG_PIXELFORMAT_32BPP
**MonitorMaxRes**: Unknown
**DriverName**: C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\amdxc64.dll
**DriverFileVersion**: 31.00.22011.4008
**DriverVersion**: 31.0.22011.4008
**DriverLanguage**: English
**DDIVersion**: 12
**FeatureLevels**: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
**DriverModel**: WDDM 2.7
**DriverBeta**: 0
**DriverDebug**: 0
**DriverDate**: 9/20/2023 7:00:00 PM
**DriverSize**: 1857032
**DriverWHQLLogo**: Yes
**WHQLDateStamp**: Unknown
**VDD**: unknown
**MiniVDD**: unknown
**MiniVDDDate**: Unknown
**MiniVDDSize**: 0
**DeviceIdentifier**: {D7B71EE2-309F-11CF-4078-D6566EC2D235}
**VendorID**: 0x1002
**DeviceID**: 0x73DF
**SubSysID**: 0x232D1458
**RevisionID**: 0x00C1
**DriverNodeStrongName**: oem41.inf:cb0ae414fb83800b:ati2mtag_Navi22:31.0.22011.4008:PCI\VEN_1002&DEV_73DF&REV_C1
**RankOfInstalledDriver**: 00CF2000
**DXVAModes**: Unknown
**DXVA2Modes**: {C58B9A06-7E89-11E1-BB00-70B34824019B}  DXVA2_ModeMPEG2_VLD  {86695F12-340E-4F04-9FD3-9253DD327460}  DXVA2_ModeH264_VLD_NoFGT  {4245F676-2BBC-4166-A0BB-54E7B849C380}  {9901CCD3-CA12-4B7E-867A-E2223D9255C3}  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeVC1_VLD  {CA15D19A-2B48-43D6-979E-7A6E9C802FF8}  {D1C20509-AE7B-4E72-AE3B-49F88D58992F}  DXVA2_ModeHEVC_VLD_Main  {EA72396A-67EC-4781-BEDE-56F498F04EF2}  {C152CA8F-738C-461B-AD89-FC292CF8F162}  {514A356C-7027-4AFF-8A60-AFD2C1F672F1}  DXVA2_ModeHEVC_VLD_Main10  {65D1FA41-58AF-453A-9CAB-5D981156DA9F}  {2DB154B6-DBB2-4079-A3FF-60D7A898A6AB}  {C74A3FD0-D713-4581-A02E-8EDFB112ACE3}  DXVA2_ModeVP9_VLD_Profile0  DXVA2_ModeVP9_VLD_10bit_Profile2  {B8BE4CCB-CF53-46BA-8D59-D6B8A6DA5D2A}  {603A4756-A864-4F91-BB62-2C935B7A1391}  {84AD67F6-4C21-419A-9F0B-24F0578906C1}  
**GraphicsPreemption**: Primitive
**ComputePreemption**: DMA
**Miracast**: Not Supported by Graphics driver
**DetachableGPU**: No
**HybridGraphicsGPUType**: Not Supported
**PowerManagementPStates**: Not Supported
**VirtualGPUSupport**: Paravirtualization 
**BlockList**: DISABLE_HWSCH
**DriverCatalogAttributes**: Universal:False Declarative:True 
**MPOMaxPlanes**: 3
**MPOCaps**: ROTATION,VERTICAL_FLIP,HORIZONTAL_FLIP,BILINEAR,HIGH_FILTER,IMMEDIATE,HDR (MPO3)
**MPOStretch**: 1.000X - 1.000X
**MPOMediaHints**: rotation, resizing, colorspace Conversion 
**MPOFormats**: R16G16B16A16_FLOAT,R10G10B10A2_UNORM,R8G8B8A8_UNORM,B8G8R8A8_UNORM
**PanelFitterCaps**: STRETCH_RGB
**PanelFitterStretch**: 16.000X - 0.167X
**HardwareSchedulingAttributes**: Supported:False Enabled:False 
**DXVADeinterlaceCaps**: 
**D3D9Overlay**: Not Supported
**DXVAHD**: Not Supported
**DDrawStatus**: Enabled
**D3DStatus**: Enabled
**AGPStatus**: Enabled

**----------------**

**CardName**: AMD Radeon(TM) Graphics
**Manufacturer**: Advanced Micro Devices, Inc.
**ChipType**: AMD Radeon Graphics Processor (0x164E)
**DACType**: Internal DAC(400MHz)
**DeviceType**: Full Device
**DeviceKey**: Enum\PCI\VEN_1002&DEV_164E&SUBSYS_7E121462&REV_CB
**DeviceStatus**: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
**DeviceProblemCode**: No Problem
**DriverProblemCode**: Unknown
**DisplayMemory**: 32819 MB
**DedicatedMemory**: 485 MB
**SharedMemory**: 32333 MB
**CurrentMode**: Unknown
**HDRSupport**: Unknown
**Topology**: Unknown
**ColorSpace**: Unknown
**ColorPrimaries**: Unknown
**Luminance**: Unknown
**MonitorMaxRes**: Unknown
**DriverName**: C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0396203.inf_amd64_5e077edb2ed5b984\B396137\amdxc64.dll
**DriverFileVersion**: 31.00.22011.4008
**DriverVersion**: 31.0.22011.4008
**DriverLanguage**: English
**DDIVersion**: 12
**FeatureLevels**: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
**DriverModel**: WDDM 2.7
**DriverBeta**: 0
**DriverDebug**: 0
**DriverDate**: 9/20/2023 7:00:00 PM
**DriverSize**: 1857032
**DriverWHQLLogo**: Yes
**WHQLDateStamp**: Unknown
**VDD**: unknown
**MiniVDD**: unknown
**MiniVDDDate**: Unknown
**MiniVDDSize**: 0
**DeviceIdentifier**: Unknown
**VendorID**: 0x1002
**DeviceID**: 0x164E
**SubSysID**: 0x7E121462
**RevisionID**: 0x00CB
**DriverNodeStrongName**: oem41.inf:cb0ae414b5a82bf9:ati2mtag_Raphael:31.0.22011.4008:PCI\VEN_1002&DEV_164E&REV_CB
**RankOfInstalledDriver**: 00CF2000
**DXVAModes**: Unknown
**DXVA2Modes**: {C58B9A06-7E89-11E1-BB00-70B34824019B}  DXVA2_ModeH264_VLD_NoFGT  {4245F676-2BBC-4166-A0BB-54E7B849C380}  {9901CCD3-CA12-4B7E-867A-E2223D9255C3}  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  {D1C20509-AE7B-4E72-AE3B-49F88D58992F}  DXVA2_ModeHEVC_VLD_Main  {EA72396A-67EC-4781-BEDE-56F498F04EF2}  {C152CA8F-738C-461B-AD89-FC292CF8F162}  {514A356C-7027-4AFF-8A60-AFD2C1F672F1}  DXVA2_ModeHEVC_VLD_Main10  {65D1FA41-58AF-453A-9CAB-5D981156DA9F}  {2DB154B6-DBB2-4079-A3FF-60D7A898A6AB}  {C74A3FD0-D713-4581-A02E-8EDFB112ACE3}  DXVA2_ModeVP9_VLD_Profile0  DXVA2_ModeVP9_VLD_10bit_Profile2  {B8BE4CCB-CF53-46BA-8D59-D6B8A6DA5D2A}  {603A4756-A864-4F91-BB62-2C935B7A1391}  {84AD67F6-4C21-419A-9F0B-24F0578906C1}  
**GraphicsPreemption**: Primitive
**ComputePreemption**: DMA
**Miracast**: Not Supported by Graphics driver
**DetachableGPU**: No
**HybridGraphicsGPUType**: Not Supported
**PowerManagementPStates**: Not Supported
**VirtualGPUSupport**: Paravirtualization 
**BlockList**: DISABLE_HWSCH
**DriverCatalogAttributes**: Universal:False Declarative:True 
**MPOMaxPlanes**: 0
**MPOCaps**: Not Supported
**MPOStretch**: Not Supported
**MPOMediaHints**: Not Supported
**MPOFormats**: Not Supported
**PanelFitterCaps**: Not Supported
**PanelFitterStretch**: Not Supported
**HardwareSchedulingAttributes**: Supported:False Enabled:False 
**DXVADeinterlaceCaps**: 
**D3D9Overlay**: Unknown
**DXVAHD**: Unknown
**DDrawStatus**: Enabled
**D3DStatus**: Enabled
**AGPStatus**: Enabled

**Comment by Tharylia** [comment]
Do you have any other modules enabled? This error is not caused by event table. It's just the victim.

**Comment by ArtistOrion** [comment]
I have other modules installed but no other ones enabled

**Comment by ArtistOrion** [comment]
I updated my graphics drivers and my BlishHUD has not crashed today, and given its frequency before I would say it is resolved. Thank you for your response earlier.
