### ISSUE TITLE
Event Table stuck at loading, using delete module crashes BlishHUD.

### ISSUE THREAD

**Issue by svefn** [Tharylia/Blish-HUD-Modules#98]
**Describe the bug**
On a new BlishHUD installation, installed Event Table 3.60 and enabled it, it is stuck at loading. Using delete module crashes BlishHUD.

Blish.HUD.1.1.1
Event Table 3.60

**Additional context**
> Blish HUD v1.1.1+Branch.tags-v1.1.1.Sha.bb767c3832d9fa95f40611458829d3fb27cc9776
12:14:26.9477 | INFO  | Blish_HUD.Program | Running Build "Branch.tags-v1.1.1.Sha.bb767c3832d9fa95f40611458829d3fb27cc9776"
12:14:26.9517 | INFO  | Blish_HUD.Program | Launched from "D:\folder\Documents\Guild Wars 2\Blish.HUD" with args "".
12:14:29.9724 | INFO  | Blish_HUD.GameIntegration.Gw2InstanceIntegration | Guild Wars 2 is running in DX11.
12:14:30.2429 | INFO  | Blish_HUD.GameIntegration.ClientTypeIntegration | Detected Guild Wars 2 client to be the Standard version.
12:14:30.8821 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "markers" ("D:\folder\Documents\Guild Wars 2\Blish.HUD\Settings\markers") was registered.
12:14:31.5476 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "events" ("D:\folder\Documents\Guild Wars 2\Blish.HUD\Settings\events") was registered.
12:14:31.8436 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "mounts" ("D:\folder\Documents\Guild Wars 2\Blish.HUD\Settings\mounts") was registered.
12:14:32.8531 | INFO  | Estreya.BlishHUD.Shared.Services.BlishHudApiService | Credentials not available.
12:14:32.8876 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "todos" ("D:\folder\Documents\Guild Wars 2\Blish.HUD\Settings\todos") was registered.
12:14:33.0046 | INFO  | Blish_HUD.GameIntegration.ClientTypeIntegration | Detected Guild Wars 2 client to be the Standard version.
12:14:33.1161 | INFO  | Blish_HUD.Modules.Module | Module "Mounts & More (Manlaan.Mounts) v1.4.4" finished loading.
12:14:33.1161 | INFO  | Blish_HUD.Modules.Module | Module "Inquest Chipset (Nekres.Inquest_Module) v0.5.0" finished loading.
12:14:33.1361 | INFO  | Blish_HUD.Modules.Pkgs.StaticPkgRepoProvider | Getting module list...
12:14:33.2341 | INFO  | Blish_HUD.Modules.Pkgs.StaticPkgRepoProvider | Getting module list...
12:14:33.2341 | INFO  | Blish_HUD.Modules.Module | Module "Pathing (bh.community.pathing) v1.4.0" finished loading.
12:14:33.2341 | INFO  | Blish_HUD.Modules.Module | Module "Todos (valorayne.bh.todos) v1.1.2" finished loading.
12:14:33.4322 | INFO  | Blish_HUD.Contexts.FestivalContext | Active festival(s): ""
12:14:34.0607 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs +DeroirsTryhardMarkers[23ms], +hero.blish.pack[7ms], -TehsTrails-HeroPoints[25ms], +TehsTrails[26ms], +tw_ALL_IN_ONE[184ms], -markers[3ms] in 822ms for map 24.
12:14:34.4102 | INFO  | Estreya.BlishHUD.Shared.Services.AccountService | Received new subtoken with permissions: Progression and Account
12:14:35.0638 | WARN  | Blish_HUD.ArcDps.SocketListener | ConnectionRefused
12:14:35.5312 | INFO  | BhModule.Community.Pathing.MarkerPackRepo.MarkerPackRepo | Found 28 marker packs from https://mp-repo.blishhud.com/repo.json.
12:14:35.5312 | INFO  | BhModule.Community.Pathing.Utility.PackHandlingUtil | Downloading pack 'Teh's Trails - Map Completion'...
12:14:41.7859 | WARN  | Blish_HUD.ArcDps.SocketListener | Start() was called more than once. Call Stop() before calling Start() again.
12:15:28.4222 | INFO  | Estreya.BlishHUD.EventTable.EventTableModule | Event Table context expired.

**Comment by svefn** [comment]
Please delete my post due to privacy issues.

**Comment by svefn** [comment]
Please delete my post due to privacy issues.

**Comment by Tharylia** [comment]
Can you enable debug logs in the overview settings of blish and reproduce the problem?
After that please send me the log via dm on discord: estreya

**Comment by svefn** [comment]
```
Blish HUD v1.1.1+Branch.tags-v1.1.1.Sha.bb767c3832d9fa95f40611458829d3fb27cc9776
16:52:49.6565 | INFO  | Blish_HUD.Program | Running Build "Branch.tags-v1.1.1.Sha.bb767c3832d9fa95f40611458829d3fb27cc9776"
16:52:49.6565 | INFO  | Blish_HUD.Program | Launched from "D:\folder\Documents\Guild Wars 2\Blish.HUD" with args "".
16:52:52.7305 | INFO  | Blish_HUD.GameIntegration.Gw2InstanceIntegration | Guild Wars 2 is running in DX11.
16:52:53.1749 | INFO  | Blish_HUD.GameIntegration.ClientTypeIntegration | Detected Guild Wars 2 client to be the Standard version.
16:52:53.9047 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "markers" ("D:\folder\Documents\Guild Wars 2\Blish.HUD\Settings\markers") was registered.
16:52:54.7547 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "events" ("D:\folder\Documents\Guild Wars 2\Blish.HUD\Settings\events") was registered.
16:52:54.8307 | INFO  | Events_Module.Meta | Loaded 70 events.
16:52:55.0807 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "mounts" ("D:\folder\Documents\Guild Wars 2\Blish.HUD\Settings\mounts") was registered.
16:52:56.1497 | INFO  | Estreya.BlishHUD.Shared.Services.BlishHudApiService | Credentials not available.
16:52:56.3282 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "todos" ("D:\folder\Documents\Guild Wars 2\Blish.HUD\Settings\todos") was registered.
16:52:56.4502 | INFO  | Blish_HUD.GameIntegration.ClientTypeIntegration | Detected Guild Wars 2 client to be the Standard version.
16:52:56.5982 | INFO  | Blish_HUD.Modules.Module | Module "Events and Metas Observer (bh.general.events) v1.0.2" finished loading.
16:52:56.5982 | INFO  | Blish_HUD.Modules.Module | Module "Mounts & More (Manlaan.Mounts) v1.4.4" finished loading.
16:52:56.5982 | INFO  | Blish_HUD.Modules.Module | Module "Inquest Chipset (Nekres.Inquest_Module) v0.5.0" finished loading.
16:52:56.6662 | INFO  | Blish_HUD.Modules.Pkgs.StaticPkgRepoProvider | Getting module list...
16:52:56.7197 | INFO  | Blish_HUD.Modules.Pkgs.StaticPkgRepoProvider | Getting module list...
16:52:56.7342 | INFO  | Blish_HUD.Modules.Module | Module "Pathing (bh.community.pathing) v1.4.0" finished loading.
16:52:56.7342 | INFO  | Blish_HUD.Modules.Module | Module "Todos (valorayne.bh.todos) v1.1.2" finished loading.
16:52:57.1027 | INFO  | Blish_HUD.Contexts.FestivalContext | Active festival(s): ""
16:52:57.6887 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs +DeroirsTryhardMarkers[25ms], +hero.blish.pack[5ms], -TehsTrails-HeroPoints[27ms], +TehsTrails[10ms], +tw_ALL_IN_ONE[198ms], -markers[2ms] in 1042ms for map 24.
16:52:58.4980 | WARN  | Blish_HUD.ArcDps.SocketListener | ConnectionRefused
16:52:59.1087 | INFO  | BhModule.Community.Pathing.MarkerPackRepo.MarkerPackRepo | Found 28 marker packs from https://mp-repo.blishhud.com/repo.json.
16:52:59.1087 | INFO  | BhModule.Community.Pathing.Utility.PackHandlingUtil | Downloading pack 'Teh's Trails - Map Completion'...
16:53:00.5525 | INFO  | Estreya.BlishHUD.Shared.Services.AccountService | Received new subtoken with permissions: Progression and Account
16:53:15.3382 | INFO  | Blish_HUD.DebugService | User activated debug logging
16:53:19.3592 | DEBUG | Blish_HUD.SettingsService | Settings were saved successfully.
16:53:25.0476 | DEBUG | Blish_HUD.SettingsService | Settings were saved successfully.
16:53:25.4806 | DEBUG | Blish_HUD.GraphicsService | Render thread stalled for 7 ms.
16:53:25.7536 | DEBUG | Blish_HUD.GraphicsService | Render thread stalled for 3 ms.
16:53:29.5230 | DEBUG | Blish_HUD.SettingsService | Settings were saved successfully.
16:53:30.0439 | DEBUG | Blish_HUD.Modules.Module | Module "Event Table (estreya.bh.eventTable) v3.6.0" run state changed to Unloading
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unload module.
16:53:30.0439 | INFO  | Estreya.BlishHUD.EventTable.EventTableModule | Event Table context expired.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unload drawer.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unloaded drawer.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unload events.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unloaded events.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unload base.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unload settings...
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unloaded settings.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unload default settings view...
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unloaded default settings view.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unload settings window...
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unloaded settings window.
16:53:30.0439 | DEBUG | Estreya.BlishHUD.EventTable.EventTableModule | Unloading states...

```

**Comment by Tharylia** [comment]
Please check now. I had some problems on my backend server

**Comment by svefn** [comment]
All good now, I didn't know there was a Discord, please delete this then, thanks.
